version: '3.9'

services:
  db:
    image: postgres:13.0-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=bookstore_dev
      - POSTGRES_PASSWORD=bookstore_dev
      - POSTGRES_DB=bookstore_dev_db
    networks:
      - backend
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - ./env.dev
    depends_on:
      - db
    networks:
      - backend
networks:
  backend:
    driver: bridge